In [3]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

df= pd.read_csv(r"C:\Users\vishn\Downloads\creditcard.csv")[:80_000] #first 80,000 rows
df.head(3)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0

In [7]:
X = df.drop(columns=['Time', 'Amount', 'Class']).values   #data cleaning, independent variables
y = df['Class'].values #it needs to be predicted variables 
f"shapes of X={X.shape} y={y.shape}, #Fraud cases={y.sum()}"    #shows how unbalanced the dataset is

'shapes of X=(80000, 28) y=(80000,), #Fraud cases=196'

In [35]:
from sklearn.linear_model import LogisticRegression #sigmoid function

mod = LogisticRegression(class_weight = {0 : 1, 1 : 2},max_iter=1000) #dictionaries
mod.fit(X,y).predict(X).sum()

171

In [37]:
from sklearn.model_selection import GridSearchCV #heart of metrics
from sklearn.metrics import precision_score, recall_score, make_scorer 

grid = GridSearchCV(
     estimator=LogisticRegression(max_iter=1000),
     param_grid={'class_weight': [{0 : 1, 1 : v} for v in range(1,4)]},
     #scoring={'precison': make_scorer(precision_score), 'recall': make_scorer(recall_score)},
     #refit='precision',
     return_train_score=True,
     cv=4,
     n_jobs=-1
)
grid.fit(X,y);

In [33]:
pd.DataFrame(grid.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_class_weight,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,mean_train_score,std_train_score
0,1.506676,0.294669,0.006003,0.003466,"{0: 1, 1: 1}","{'class_weight': {0: 1, 1: 1}}",0.99405,0.99835,0.99945,0.99780,0.997413,0.002030,1,0.999617,0.998667,0.998300,0.998733,0.998829,0.000484
1,1.539306,0.305993,0.006174,0.003571,"{0: 1, 1: 2}","{'class_weight': {0: 1, 1: 2}}",0.99025,0.99840,0.99960,0.99805,0.996575,0.003697,2,0.999633,0.998733,0.998550,0.998900,0.998954,0.000411
2,1.334061,0.164252,0.004016,0.004016,"{0: 1, 1: 3}","{'class_weight': {0: 1, 1: 3}}",0.98730,0.99845,0.99960,0.99815,0.995875,0.004980,3,0.999617,0.998800,0.998667,0.998983,0.999017,0.000364